### ISSUE TITLE
RuntimeError: Can't find MKL libraries

### ISSUE THREAD

**Issue by WuShichao** [gwastro/pycbc-inference-paper#3]
Hello, I use the docker version, but get this error, no MKL.

(pycbc-software) [pycbc@24f913201669 GW151226]$ ls
extract_independent_samples.sh  gw151226_inference.ini  run_pycbc_inference_gw151226.sh
(pycbc-software) [pycbc@24f913201669 GW151226]$ pwd
/home/pycbc/pycbc-inference-paper/run_files/GW151226
(pycbc-software) [pycbc@24f913201669 GW151226]$ bash run_pycbc_inference_gw151226.sh 
1135136340
1135136356
1135136238
1135137262
/home/pycbc/pycbc-software/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-06-03 16:42:42,073 Using seed 12
Traceback (most recent call last):
  File "/home/pycbc/pycbc-software/bin/pycbc_inference", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==1.12.3', 'pycbc_inference')
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-1.12.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pycbc_inference", line 195, in <module>
    ctx = scheme.from_cli(opts)
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-1.12.3-py2.7-linux-x86_64.egg/pycbc/scheme.py", line 262, in from_cli
    ctx = MKLScheme()
  File "/home/pycbc/pycbc-software/lib/python2.7/site-packages/PyCBC-1.12.3-py2.7-linux-x86_64.egg/pycbc/scheme.py", line 149, in __init__
    raise RuntimeError("Can't find MKL libraries")
RuntimeError: Can't find MKL libraries
(pycbc-software) [pycbc@24f913201669 GW151226]$

**Comment by soumide1102** [comment]
Hi, 
This says you don't have MKL libraries set up in your environment. Changing `PROCESSING_SCHEME=mkl` to `PROCESSING_SCHEME=cpu` in the `run_pycbc_inference_gw151226.sh` script should be the fix.
